# Generated by Django 3.1.7 on 2021-06-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='ordernumber',
        ),
    ]
