# Generated by Django 3.1.7 on 2021-07-02 21:21

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20210616_0247'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aktivite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CImages',
            new_name='AktiviteImages',
        ),
        migrations.CreateModel(
            name='UserContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('menu', 'menu'), ('content', 'content')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('konum', models.CharField(max_length=225)),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AktiviteImagess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('usercontents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktivite.usercontents')),
            ],
        ),
    ]
