# Generated by Django 3.1.7 on 2021-07-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktivite', '0002_auto_20210703_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivite',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
