# Generated by Django 3.1.7 on 2021-04-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
